#include <iostream>
#include <string>
#include <vector>
#include <iostream>
#include <algorithm>
#include "tclap/CmdLine.h"
#include "Id3v2.hpp"
/******************************************************
    Main.cpp is used for parsing the given file and 
    passing it on to the function. Do not use this 
    file for anything beying making passing on the
    parsed file name to the actual backend.
******************************************************/
int main(int argc, char *argv[])
{
    try
    {

        TCLAP::CmdLine Cmd("IED3 Help Message|Generated by TCLAP.", ' ', "0.01");
        TCLAP::ValueArg<std::string> FileArg("f", "Filename", "Filename to be included", true, "Everything", "String");
        Cmd.add(FileArg);
        TCLAP::SwitchArg Output("o", "output", "Output file name", Cmd, false);
        Cmd.parse(argc, argv);
        std::string Filename = FileArg.getValue();
        std::string Output_Filename;
        if (Output.getValue() == false)
        {
            Output_Filename = "Out.txt";
        }
        ID3v2::IData AP;
        AP.Read_Header(Filename);
    }
    catch (TCLAP::ArgException &e)
    {
        std::cerr << "Error" << e.error();
    }
}
